### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by GrafdeFer** [GrafdeFer/reacr-redux-express-todo-list#1]
Client:

- [ ] - Login page (Router)

- [ ] - Register page (Router)

- [ ] - Store

- [ ] - Reducers

- [ ] - Actions

- [ ] - API (Axios)

- [ ] - Material-UI styling
